### ISSUE TITLE
Quote marks get removed.

### ISSUE THREAD

**Issue by ytRino** [tomorrowkey/adb-peco#4]
i found adbp removes quote marks.
ex:

```
$ adbp shell am start -n you.app/your.app.TargetActivity --es "test" "Can you see me?"

adb -s 192.168.56.101:5555 shell am start -n you.app/your.app.TargetActivity --es test Can you see me?
```

This command brings you only `"Can"` with `test` extra key.
Of course, with quotes,

```
adb -s 192.168.56.101:5555 shell am start -n you.app/your.app.TargetActivity --es "test" "Can you see me?"
```

will let you get `"Can you see me?"` correctly :smiley: .
i think that is unwanted behavior. (i don't know this is environment dependent behavior or not. sorry)

**Comment by tomorrowkey** [comment]
Thank you for reporting.
This issue will be solved ver 2.0 (Implemented by ruby version).

**Comment by tomorrowkey** [comment]
See at e09675611f35f1d54d9be94dd1b224a20be41497

**Comment by tomorrowkey** [comment]
v2.0 has been released.
Please try this version to confirm the issue solved then close the issue.

**Comment by tomorrowkey** [comment]
@ytRino v2.0 has been released.
Please try this version to confirm the issue solved then close the issue.

**Comment by tomorrowkey** [comment]
If you face the same issue, please reopen the issue.

**Comment by ytRino** [comment]
@tomorrowkey Oops. Sorry I didn't noticed. And it seems working fine. thx!
